---
name: Logstash Syntax
on:
  push:
    tags:
      - v*
    branches:
      - main
      
  pull_request:
  
  repository_dispatch:

jobs:
  build-and-run-pipeline:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        logstashversion: [7]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: List Workdir
        run: |
          pwd
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gpg
          wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
          echo "deb https://artifacts.elastic.co/packages/${{ matrix.logstashversion }}.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic.list
          sudo apt-get update
          sudo apt-get install logstash
          sudo /usr/share/logstash/bin/logstash-plugin install logstash-codec-csv
          mkdir -p /tmp/logstash/data /tmp/logstash/logs

      - name: Test with Logstash
        run: |
          /usr/share/logstash/bin/logstash  --path.settings /etc/logstash/ --path.config '*conf' --path.data /tmp/logstash/data --path.logs /tmp/logstash/logs 
